# Generated by Django 3.0.5 on 2020-06-13 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=50)),
                ('release_money', models.IntegerField()),
                ('join_date', models.DateField()),
                ('fifa_rating', models.IntegerField()),
                ('athlate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prac3app.Player')),
            ],
        ),
    ]
