# Generated by Django 3.0.5 on 2020-06-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prac3app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdetails',
            name='fifa_rating',
            field=models.IntegerField(choices=[(1, ' 95+ '), (2, ' 90+'), (3, ' 85+'), (4, ' 80+')]),
        ),
    ]
